"""Add new fields for Users

Revision ID: 49ece4bb35a8
Revises: a430d9078166
Create Date: 2025-09-25 16:16:35.730661

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "49ece4bb35a8"
down_revision: Union[str, Sequence[str], None] = "a430d9078166"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("First_name", sa.String(length=200), nullable=False)
    )
    op.add_column(
        "users", sa.Column("Last_name", sa.String(length=200), nullable=False)
    )
    op.add_column("users", sa.Column("NickName", sa.String(length=20), nullable=False))
    op.add_column("users", sa.Column("Created_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "Created_at")
    op.drop_column("users", "NickName")
    op.drop_column("users", "Last_name")
    op.drop_column("users", "First_name")
    # ### end Alembic commands ###
