"""Fix last_name

Revision ID: 64fc623405fa
Revises: d5de9639de67
Create Date: 2025-09-25 17:11:04.349513

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "64fc623405fa"
down_revision: Union[str, Sequence[str], None] = "d5de9639de67"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("last_name", sa.String(length=200), nullable=False)
    )
    op.drop_column("users", "fast_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "fast_name", sa.VARCHAR(length=200), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("users", "last_name")
    # ### end Alembic commands ###
