"""Add Booking

Revision ID: e7e8b81e31e4
Revises: 833f52fdce36
Create Date: 2025-09-30 17:09:16.486030

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "e7e8b81e31e4"
down_revision: Union[str, Sequence[str], None] = "833f52fdce36"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
