"""Add new fields for Users

Revision ID: 1ceee0785916
Revises: 49ece4bb35a8
Create Date: 2025-09-25 16:50:01.573513

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1ceee0785916"
down_revision: Union[str, Sequence[str], None] = "49ece4bb35a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("first_name", sa.String(length=200), nullable=False)
    )
    op.add_column(
        "users", sa.Column("fast_name", sa.String(length=200), nullable=False)
    )
    op.add_column("users", sa.Column("nickName", sa.String(length=20), nullable=False))
    op.add_column("users", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.drop_column("users", "Created_at")
    op.drop_column("users", "First_name")
    op.drop_column("users", "Last_name")
    op.drop_column("users", "NickName")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "NickName", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "Last_name", sa.VARCHAR(length=200), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "First_name", sa.VARCHAR(length=200), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "Created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("users", "created_at")
    op.drop_column("users", "nickName")
    op.drop_column("users", "fast_name")
    op.drop_column("users", "first_name")
    # ### end Alembic commands ###
